### ISSUE TITLE
Error in video playing

### ISSUE THREAD

**Issue by ffallahi** [HbbTV-Association/ReferenceApplication#13]
I did tests related to video player. When receiver doesn't support these players or can't pass the test, receiver didn't show error message. For long time you should wait and still receiver is trying to play. While it should show that it can't play video in short time. Some times, I waited for long time and there was not shown any error and just receiver was trying for playing.

**Comment by juhajoki** [comment]
blue key (engineer view) can be used to check if the player is stuck. 
more visible error message could be shown as well. 

I close this and open a more specific ticket about this.
