### ISSUE TITLE
MS3 scheme not supported in video tag with src attribute

### ISSUE THREAD

**Issue by zooltar** [HbbTV-Association/ReferenceApplication#17]
Hello,

I noticed in videoplayer scripts, you create a video object with a type attribute, however, the [HTML5](https://www.w3.org/TR/2011/WD-html5-20110113/video.html#the-source-element) media element specification says that there is no type attribute on <video>. If you want to pass mime type you MUST use <source> attribute.

Best regards,
Przemysław Mazur

**Comment by jpiesing** [comment]
Is this a duplicate of #11 ?

**Comment by zooltar** [comment]
That's correct, let's stick to #11
