### ISSUE TITLE
Playready Licence URL reset

### ISSUE THREAD

**Issue by juhajoki** [HbbTV-Association/ReferenceApplication#18]
The issue is about test 2.1.1, a Playready video test.
- Test 2.1.1 is working if no other PlayReady are run before
- but FAILS run another test case is run prior to 2.1.1, e.g. after 2.1 or after 2.1.2

Both test streams 2.1 and 2.1.2 use Initiator to overwrite License Acquisition URL. At the start of test stream 2.1.1, the License Acquisition URL from the previous test stream is still set and therefore the player fails to play.

The License Acquisition URL has to be set back explicitly (cancelled) using License URL override initator again.

Ref: HbbTV Content Protection using Microsoft PlayReady V1.0 Section 3.1.2.5

**Comment by juhajoki** [comment]
fix pushed to staging 26th Feb

**Comment by zooltar** [comment]
Is the patch live on the staging URL? I am seeing the same behavior, license is not reacquired with the following scenario:

- choose 2.1.1 AVC 1080p video (v5) - works
- choose 2.1 AVC 1080p video - works
- choose 2.1.1 AVC 1080p video (v5) - video don't start playing

Test 2.1 uses sendDRMMessage to override LA_URL through application/oipfDrmAgent which has global effect for the webpage/application (it's configured per window ID). When test 2.1.1 is run again it's using the overridden LA_URL as it should. If the intention of TC is to set LA_URL per playback, it should set it each time (or clear it) using the OIPF DRM agent API as it's a global setting.
