### ISSUE TITLE
consider providing transport stream signalling the reference app

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#19]
It has been noted that some HbbTV TVs don't have an interface to run broadcast-independent apps directly. This is a small barrier to using the reference app. Could HbbTV consider removing this barrier by supplying a simple transport stream that can be used to launch the reference app?
I don't know if such a simple TS could signal the reference app directly or if it would need a trivial autostart broadcast-related app which just launched the reference app.

**Comment by juhajoki** [comment]
we will provide a TS that includes direct links to staging and production versions of the app.

**Comment by juhajoki** [comment]
Stream created and link added to readme.md and http://refapp.hbbtv.org/

direct access: http://refapp.hbbtv.org/videos/refapp_10_04_2019.ts
