### ISSUE TITLE
ExpressPlay license expired

### ISSUE THREAD

**Issue by zooltar** [HbbTV-Association/ReferenceApplication#20]
ExpressPlay license with is used in test 2.1.2 AVC 1080p video (v3) in PlayReady tab has expired on 28.02.2019.

**Comment by zooltar** [comment]
License has also expired for Marlin related test cases

**Comment by juhajoki** [comment]
licenses refreshed!

**Comment by zooltar** [comment]
@juhajoki Would you refresh it once again, please? It expired once again on 06.06.2021

Thanks!

**Comment by jpiesing** [comment]
Re-opening @juhajoki

**Comment by juhajoki** [comment]
refreshed again. sorry for the inconvenience. again.

**Comment by zooltar** [comment]
Would you get a new one? Current once expired last week.

Thanks
