### ISSUE TITLE
Add chunked segments to LL DASH

### ISSUE THREAD

**Issue by juhajoki** [HbbTV-Association/ReferenceApplication#21]
“DVB Document A168”, clause “4.2.9 Constraints for low latency content” there are two way to “implement” LL-DASH.
•	chunked segments
•	short segments (this is done already in staging)
I also understood the DASH-IF & DVB preferred way is the one based on “chunked segments” which require “extra” signaling in the MPD by means of @availabilityTimeOffset and 
@availabilityTimeComplete.

**Comment by jpiesing** [comment]
> “DVB Document A168”, clause “4.2.9 Constraints for low latency content” there are two way to “implement” LL-DASH.
> • chunked segments
> • short segments (this is done already in staging)
> I also understood the DASH-IF & DVB preferred way is the one based on “chunked segments” which require “extra” signaling in the MPD by means of @availabilityTimeOffset and
> @availabilityTimeComplete.

The comment about what is in staging is IMHO not quite right.
Short segments are just current segments (1 moof/mdat pair per segment) with duration of (say) 1s.
Chunked segments divide each segment into multiple CMAF chunks which (IMHO) are each a moof/mdat pair. Support for this is included in the existing (previous) DASH specs but not tested.
The full low latency approach requires additional MPD signalling but it also requires other (deeper) changes to the DASH player.
LL content should however be backwards compatible to an existing DASH player.

**Comment by juhajoki** [comment]
closing as not relevant right now. Can be re-opened as necessary or created as a new ticket.
