### ISSUE TITLE
better documentation when using app for integration device testing

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#22]
One of the goals of the reference app is to be used for integration testing of HbbTV devices. The documentation doesn't appear to be good enough for this - at least not obviously. Test engineers who are not HbbTV experts need a clearly defined set of steps to be taken & the results expected for each step.

**Comment by juhajoki** [comment]
I assume this means firstly improving the language on 

1) how to signal the ref app for your device (use the MPEG-2 TS or insert the AIT to your local signaling)
2) explain the test areas (No DRM, Playready, Marlin, Clearkey, Live) better
3) re-write the test task descriptions and include screenshots if possible especially for subtitling and event tests
4) verify that color keys for audio and sub changing are documented also here and not just a brief hint at the application

secondly (expert topics)
1) how to fork the app
2) how to edit the config.json to include one's own tests

**Comment by jpiesing** [comment]
> I assume this means firstly improving the language on
> 
>     1. how to signal the ref app for your device (use the MPEG-2 TS or insert the AIT to your local signaling)
> 

Not the focus of this comment.

>     2. explain the test areas (No DRM, Playready, Marlin, Clearkey, Live) better
> 

Yes.

>     3. re-write the test task descriptions and include screenshots if possible especially for subtitling and event tests
> 

Yes. This is the priority - document it well enough that a test engineer can read the document, follow it, know what to expect and report issues where something isn't what is expected.

>     4. verify that color keys for audio and sub changing are documented also here and not just a brief hint at the application
> 

Yes.

> 
> secondly (expert topics)
> 

No.

**Comment by juhajoki** [comment]
process has started: https://github.com/HbbTV-Association/ReferenceApplication/blob/master/doc/walkthrough.md

**Comment by jpiesing** [comment]
> process has started: https://github.com/HbbTV-Association/ReferenceApplication/blob/master/doc/walkthrough.md

This is a good start and certainly will help people understand what is going on but IMHO it doesn't quite go far enough.

The original problem description said "Test engineers who are not HbbTV experts need a clearly defined set of steps to be taken & the results expected for each step."

**Comment by aleksanterisaarela** [comment]
> This is a good start and certainly will help people understand what is going on but IMHO it doesn't quite go far enough.
> 
> The original problem description said "Test engineers who are not HbbTV experts need a clearly defined set of steps to be taken & the results expected for each step."

First complete draft of the walkthrough is now done. Some of the previously shown images have been replaced with a .gif-file in order to highlight necessary steps and expected results.

In the walkthrough, the focus is now on practicalities and not so much on underlying technologies.
