### ISSUE TITLE
DRM license discrepancy between git and staging/production versions

### ISSUE THREAD

**Issue by zooltar** [HbbTV-Association/ReferenceApplication#24]
Both DRM's licenses (PR and Marlin) are outdated on master branch as opposed to staging/production versions (license is valid till 08.06.2019)

https://github.com/HbbTV-Association/ReferenceApplication/blob/90187457ba4833d46a059a85acff654bf82d39e7/src/catalogue/config.json#L175

https://github.com/HbbTV-Association/ReferenceApplication/blob/90187457ba4833d46a059a85acff654bf82d39e7/src/catalogue/config.json#L295

**Comment by juhajoki** [comment]
fixed.
