### ISSUE TITLE
In-band subtitles subtitles mode hidden by default

### ISSUE THREAD

**Issue by zooltar** [HbbTV-Association/ReferenceApplication#25]
Here are some problems we have identified:

- At beginning, all subtitle tracks mode is set to hidden which means that they are to be downloaded but not displayed (why?)
- The number of "valid" text tracks (except "metadata" ones) and then use the count as max-index (but if metadata tracks are first, then it can fail)

https://github.com/HbbTV-Association/ReferenceApplication/blob/a7558da110741003b77978ea8669d02437f80798/src/videoplayer/videoplayer_basic.js#L152-L203

**Comment by juhajoki** [comment]
@joonajarvinen @Murmur care to comment?

**Comment by joonajarvinen** [comment]
This is fixed and updated in next release soon

**Comment by juhajoki** [comment]
fix is applied to staging instance
