### ISSUE TITLE
Microsoft Playready LAURL changes

### ISSUE THREAD

**Issue by Murmur** [HbbTV-Association/ReferenceApplication#26]
Old Microsoft LAURL license urls in ReferenceApp have recently had problems with some of the older HbbTV devices. The issue is there is time based policies being added to a license for a device that does not support time based policies on non-persistent licenses(its pre-PlayReady 3).

PlayReady3+ clients support all time based policies such as first play expiration on non-persistent license only when realtimeexpiration is set (as a param as realtime:true). Set persist to true for time based policies on all versions of playready. This means the license is stored on the device. Non-persist license is kept in RAM for the duration of runtime session.

Fix is to remove `firstexp:60` attribute from the license.

**Old LAURL**
`https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(kid:header,sl:2000,persist:false,firstexp:60,contentkey:EjQSNBI0EjQSNBI0EjQSNg==)`

**New LAURL**
`https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(kid:header,sl:2000,persist:false,contentkey:EjQSNBI0EjQSNBI0EjQSNg==)` 

Microsoft also provides old versioned LAURL hostnames for legacy testing.
http://testweb.playready.microsoft.com/Server/ServiceVersioned

If you use the following URL as a license url it will output device info rather than a license. You may need a way to intercept https request-response to debug xml documents.
https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(msg:clientinfo)

**Comment by juhajoki** [comment]
this fix has been pushed to master
