### ISSUE TITLE
HTML5 player pauses already paused video object

### ISSUE THREAD

**Issue by zooltar** [HbbTV-Association/ReferenceApplication#27]
This can be spotted in the following testcase

> 1.5 Advert insertion (v5)

during startup it should be the `load()` method that is called to preload content, and not `pause()`. Calling pause() on already paused video object is unecessary

https://github.com/HbbTV-Association/ReferenceApplication/blob/a7558da110741003b77978ea8669d02437f80798/src/videoplayer/videoplayer_html5.js#L474-L501

**Comment by juhajoki** [comment]
@joonajarvinen comment, please

**Comment by joonajarvinen** [comment]
fixed. updated in next release

**Comment by juhajoki** [comment]
fix is available in staging instance.
