### ISSUE TITLE
PlayReady LA_URL is completed asynchronously

### ISSUE THREAD

**Issue by zooltar** [HbbTV-Association/ReferenceApplication#28]
The TC calls "sendDRMMessage()" with LA_URL override, then TC does not wait for "sendDRMMessage()" completion, and starts license downloading process, the override "sendDRMMessage()" is completed asynchronously, later on... but the license downloading process is already started, using URL that was not overridden.

Test case is using application/oipfDrmAgent object API. Test 2.1 uses sendDRMMessage to override LA_URL through application/oipfDrmAgent which has global effect for the webpage/application (it's configured per window ID). When test 2.1.1 is run again it's using the overridden LA_URL as it should.

If the intention of TC is to set LA_URL per playback, it should set it each time (or clear it) using the OIPF DRM agent API as it's a global setting.

Reproduction:
1. Start PlayReady test cases in the following scenario:

- 2.1.1 AVC 1080p video (v5)
- 2.1 AVC 1080p video
- 2.1.1 AVC 1080p video (v5)

Actual result:
Application calls sendDRMMessage(LA uri override), this blocks for a moment - waiting for SC update in DRM backend...
Application starts downloading license without waiting for the override to complete license downloading uses the original URL, not the overloaded one
sendDRMMessage() completes
override is set on DRM backend instance... too late
server rejects license download request.

Expected result:
Application should explicitly wait for the override command to be completed, and only then start downloding licence

**Comment by juhajoki** [comment]
reproduced with many devices. @joonajarvinen will take a look and apply the fix

**Comment by juhajoki** [comment]
fix is applied to staging instance.

**Comment by zooltar** [comment]
is it? I cannot find a commit related to this issue and it's still reproducible

**Comment by juhajoki** [comment]
to be re-checked...

**Comment by YifanZhangSraf** [comment]
I run into almost the same issue with zooltar.

Test 2.1.1 can be played properly if I run it first after a device reboot.

If I run Test 2.1.1 after Test 2.1, screen is pretty much all green:
Test 2.1 uses sendDRMMessage to override LA_URL through oipfDrmAgent object.  ==> The video is played properly.
After Test 2.1, Test 2.1.1 runs with the overridden LA_URL set by Test 2.1.  ==> The video is playing with a green screen.

I wonder the intention of Test 2.1.1 is to play a video with the LA_URL parsed from the stream mpd, not using the overridden LA_URL set by Test 2.1.
In the end of Test 2.1, it should clear LA_URL by using the sendDRMMessage API with an empty <LA_URL> tag in DrmMessage,
or destroy the oipfDrmAgent object.

Reproduction:

Start PlayReady test cases in the following scenario:
2.1 AVC 1080p video
2.1.1 AVC 1080p video (v5)

**Comment by bobcampbell-eurofins** [comment]
Does this still need work or can it be resolved?

**Comment by bobcampbell-eurofins** [comment]
Hi @Murmur can you give an update on this issue?

**Comment by Murmur** [comment]
Asynchronous laurl function invocations were fixed earlier, new production and staging has a fix to clear an overridden laurl value in an oipfDrmAgent object so that it does not carry over to the next test such as `laurl embedded in manifest`, see `YifanZhangSraf` comment.
https://refapp.hbbtv.org/production/catalogue/
https://refapp.hbbtv.org/staging/catalogue/
