### ISSUE TITLE
 Microsoft Playready LAURL versioning

### ISSUE THREAD

**Issue by juhajoki** [HbbTV-Association/ReferenceApplication#29]
Microsoft offers legacy playready server versions at http://testweb.playready.microsoft.com/Server/ServiceVersioned

Consider adding these as a configuration option to catalogue config file and/or document them for troubleshooting purposes.

**Comment by bobcampbell-eurofins** [comment]
How does this overlap with the various open PR issues - is this something that still needs to be considered?
