### ISSUE TITLE
About screen

### ISSUE THREAD

**Issue by juhajoki** [HbbTV-Association/ReferenceApplication#30]
Impelement a about screen in "Settings" with the following information

Build date and version (Production/Staging YYYY/MM/DD)

Logging warning (Anonymous usage information is collected, including number of visitors and amount of total data transferred. Individual addresses are not stored.)

**Comment by juhajoki** [comment]
to be implemented in #54

**Comment by Murmur** [comment]
Added an app context build to `Settings/Reload Catalogue` info text, context path identifies `/production, /testing` use.

**Comment by Murmur** [comment]
Added `Settings/About` menu item. 
https://refapp.hbbtv.org/production/catalogue/
https://refapp.hbbtv.org/staging/catalogue/
