### ISSUE TITLE
Set mode MSE-EME on HbbTV devices

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#32]
The MSE-EME mode was intended for non-HbbTV devices such as PCs and consoles.
HbbTV is working on adding MSE to the spec for HbbTV 2.0.3.
Members who already support MSE-EME may find it useful to be able to run this on HbbTV and see what happens.
Is this mode expected to work on HbbTV devices that support MSE?
Is there any reason why it would not work on HbbTV devices that support MSE?

**Comment by Murmur** [comment]
MSE_EME mode in a reference application tries to be a platform agnostic so PC browser, HbbTV or any MSE compatible platform should work. We however have run tests mostly on PC browsers. Player framework is dashjs.

**Comment by jpiesing** [comment]
There is some evidence that MSE is supported on >50% of the HbbTV terminals. Wld you be able to try it on some & see if it works on any of them?

**Comment by juhajoki** [comment]
we will run test and report an anonymous statistic.

**Comment by juhajoki** [comment]
Our estimation based on initial testing is ~ 23 %
