### ISSUE TITLE
Before exit analytics

### ISSUE THREAD

**Issue by EstebanBP** [HbbTV-Association/ReferenceApplication#35]
I've just started to do some things with HbbTV and I've been using this project as my guide to solve most of my doubts. Everything it's quite well explained but I'd like to get some analytics just before user leaves.
Is it possible to know when the user is about to leave/change channel/turn off tv/ ...?

Thanks in advance

**Comment by jpiesing** [comment]
This isn't really the right place for this sort of question but I can't recommend anywhere better so ...

You might try registering for an unload event and a beforeunload event. 
Both of those should be fired on a channel change but you might want to test a couple of devices.
You might also test if the Beacon API is supported and use that if it's there.

Nothing will help you if someone turns off a TV at the power socket though.

**Comment by EstebanBP** [comment]
@jpiesing 
Thank you so much for your answer, I'll try with those events because I think Beacon API is not supported in most the devices I tried
I know this wasn't the best place but I have not found yet any other place to ask questions or share experiences with other developers about hbbtv, some kind of forum, slack/discord channel o something like that

**Comment by jpiesing** [comment]
@EstebanBP 
> I know this wasn't the best place but I have not found yet any other place to ask questions or share experiences with other developers about hbbtv, some kind of forum, slack/discord channel or something like that

Would you have any preference for somewhere to ask questions / share experiences? HbbTV has talked about forums, dedicated areas of stackoverflow & other ideas but never reached a conclusion.

**Comment by jpiesing** [comment]
@EstebanBP You might also look at onbeforeunload / the beforeunload event on window. That appears to be used by some of the HbbTV unit tests so it should work.

**Comment by EstebanBP** [comment]
@jpiesing A forum about hbbtv development would be great and I think it would help a lot of developers in my opinion

About onbeforeunload and beforeunload window events, I've tried them but I've already found a couple of devices that do not seem to fire it (or atleast I'm not able to catch it) even though it works in most of them
