### ISSUE TITLE
Testing HTML5 player on HbbTv 2.0.2 emulator

### ISSUE THREAD

**Issue by DevMahix** [HbbTV-Association/ReferenceApplication#36]
I have been playing around with the Reference Application. I set up the Vewd TV Emulator and run the application using the following user agent: HbbTV/1.5.1 (;Sonic; VX600WDR; 1.14.0; ; dd5528b6-d0a9-40a8-acdb-21fa2eabeb2e;)
When I ran  1.5 Advert insertion (v5) on HBB 2.0.1 mode, when the first ad is about to end, the app stops. The suspend event gets fired for some reason. Am I doing something wrong or is this a bug?

**Comment by juhajoki** [comment]
sorry, this bug was unassigned and went undetected. Were you able to solve this or is this still an issue?

**Comment by DevMahix** [comment]
> sorry, this bug was unassigned and went undetected. Were you able to solve this or is this still an issue?

Unfortunately not.

**Comment by juhajoki** [comment]
@DevMahix, this information is straight from Vewd:
The Vewd TV Emulator does not support HbbTV officially. It supports HTML5 standards, adaptive streaming standards, as well as dynamic ad insertion technologies such as MPEG-DASH periods and HLS discontinuity, but it doesn't support any HbbTV APIs or events. Vewd recommends using a retail device (e.g TV) to run HbbTV tests.
