### ISSUE TITLE
PlayReady not playing with Edge on Windows 10

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#38]
Playback with PlayReady isn't working with Edge on Windows 10.
It might be my PC but I wonder if it's the same issue as #37 or something else?

**Comment by juhajoki** [comment]
Please try from https://refapp.hbbtv.org/testing/catalogue/, tasks 2.2 or 2.7 - the ones with correct https links seem to work better. This finding points to the same issue as in #37 . 

Perhaps we need to move to https across the board and check all the links and references.

**Comment by jpiesing** [comment]
It just hangs with the little rotating pattern in the middle.
![image](https://user-images.githubusercontent.com/8490792/108114457-1b952b00-7099-11eb-9b0e-c4fb398e0691.png)

**Comment by juhajoki** [comment]
Issue and discussion related to this from the DASH.js issue tracker: https://github.com/Dash-Industry-Forum/dash.js/pull/3517#issuecomment-829010657

**Comment by Murmur** [comment]
EdgeChromium must have made changes how GPU+CPU environment is trusted. I have two Win10 PCs where EdgeLegacy played `playready`  but fails on EdgeChromium release. Same two machines run fine Chrome+Firefox `widevine` and EdgeChromium+widevine streams.

My most recent Win10 laptop is running fine both EdgeChromium+playready and EdgeChromium+widevine.

I have tried various flags in EdgeChromium, open `edge://flags/` tabsheet.

- search `decrypt` and try disabling widevine
- search `override` and enable `override software rendering list`
- serach `angle` and try `Choose ANGLE backend` options
- search `raster` and try `GPU rasterization` and `Zero-copy rasterizer`
- search `Skia` and try `Skia API` options

Some of the angle backends break both widevine and playready, some does not let playready Laurl invoked at all, some let playready laurl invocation but then demuxer error is raised, some let widevine work fine. 

None of the options fix playready playback problems on my two older Win10 boxes. Use `edge://edge-urls` to list internal addresses, such as `edge://gpu` to validate hardware acceleration and drm status.

**Comment by Murmur** [comment]
My old `Win10/EdgeChromium 93.0.961.52` browser.
**edge://flags**
```
Override software rendering list = enabled
Choose ANGLE graphics backend = D3D11
PlayReady DRM for Windows 10  = enabled
Widevine DRM = disabled
Skia API for compositing = enabled
```

[Dashjs nighthly](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html) is sometimes playing Playready and Refapp/Playready content but not always. Restarting MSEdge may help or not, need more testing.

**Comment by bobcampbell-eurofins** [comment]
Hi, what more needs to be done to resolve this? are you looking for input from IITF members? If so please explain what to do...

**Comment by juhajoki** [comment]
Now content playback is working.
Windows 10 21H2 
Edge 98.0.1108.43
RefApp Staging, assets with Playready protection

Further notes about Playready playback with different security settings and platforms, #41
