### ISSUE TITLE
info digital channel tv

### ISSUE THREAD

**Issue by ascomputer** [HbbTV-Association/ReferenceApplication#42]
hi everyone, I have installed ReferenceApplication
on debian 10 and it works fine, i can't figure out how to integrate it on a digital terrestrial tv channel, can someone help me with some information? thank you

**Comment by juhajoki** [comment]
hello, you need an AIT generator / HbbTV inserter that will add the necessary metadata to your digital channel. There are plenty of commercial solutions available, and some open source as well. 

My company, Sofia Digital, makes one, but you can google for AIT generator / HbbTV inserter for more options.
