### ISSUE TITLE
Using mp4 progressive file

### ISSUE THREAD

**Issue by salvaaod** [HbbTV-Association/ReferenceApplication#43]
Hi I am trying thes reference application in a production environment and works very well. The scenario is a small DTT Local station, our multiplexer generates de right AIT and PMT tables and we have hosted the sample application in our servers and all works fine. We have modified the menus to our needs through config.json and I can say that the application is almost production ready. 

We plan only to use VOD with no encryption, no live content, therefore we will like to use  simple single file mp4 format instead of DASH, I have tried directly to use a mp4 url for the url video definition in the config.json with mixed results, some devices are ok but some don't.

First of all, is it feasible at all using mp4 instead of dash for VOD content ? in case that this is feasible, How can I do it the right way?, should I use a different "app" number ?

Thanks in advance.

**Comment by Murmur** [comment]
This application focus on dash playback (dashjs for MSE-EME or native dash support) so using a simple .mp4 file may or may not work. Did you edit video player to always playback using a HTML5 `<video>` tag without Hbbtv oipf objects initializations?

**Comment by salvaaod** [comment]
> This application focus on dash playback (dashjs for MSE-EME "PC browsers" or device's native dash support) so using a simple .mp4 file may or may not work. Did you edit video player to always playback using a HTML5 `<video>` tag without Hbbtv oipf objects initializations?

I am using the Reference Application "as is" no modifications, I am only using a mp4 video on the URL.
 
> Is your mp4 files a fragmented mp4 (multiple MOOF/MDAT pairs) or a simple mp4 with MOOV headers at the start for a faststart use? Simple mp4 with a faststart tend to have a better compatibility on various devices.

Yes, simple mp4 with MOOV headers, they are created with ffmpeg with the option "-movflags faststart"

So, going to the concrete point, Does the "app" option in the config.json has any effect? That is what I was wondering if the Reference Application has already some provisions to play mp4.

**Comment by jpiesing** [comment]
I've not looked at the code so this may be completely wrong but ....
In HbbTV 1.5 mode, the <object> element has a type attribute that will be set differently for MP4 and DASH. See HbbTV 9.4.3 for DASH;

![Screenshot_20210514_110905](https://user-images.githubusercontent.com/8490792/118249424-b5f0e900-b4a5-11eb-98a5-8b51b0d3fc7b.png)

For MP4 that attribute would need to be set to "video/mp4".

Some implementations may work if the type attribute is set wrongly and others may not.

In HbbTV 2 mode, the video element has no such equivalent. As far as I can remember, you can choose HbbTV 1.5 mode vs HbbTV 2 mode on the settings of the app. 

You should probably check which mode was used in your tests and try the other one to see if more devices work or if it's just different ones that don't work.
