### ISSUE TITLE
Not able to setup the project on localhost server!

### ISSUE THREAD

**Issue by hiren3897** [HbbTV-Association/ReferenceApplication#44]
Hello @juhajoki,
I hope you are doing great.

I tried to learn and set up the project using the installation guide, but I cannot set up this application on localhost for testing.

can you please tell me after cloning the project, what further steps I have to follow to run the project on localhost, or do I have to use the server to run the project ?

Thank you in advance for your help!!

**Comment by hiren3897** [comment]
Hello Team,
Can anyone help me to clear my doubts?

I want to develop an Hbbtv application that provides a transparent overlay on the TV and when clicked using any button from the remote control, for example, green, it should start the video configured in the player.

Is it possible to do so using the Hbbtv reference application ?
Please let me you.

Thank You.

**Comment by juhajoki** [comment]
hello,
instructions are at https://github.com/HbbTV-Association/ReferenceApplication/blob/master/doc/installation_testing.md
you need to setup a common www-server (apache or nginx will work fine) with PHP support. Then after cloning the project to a directory accessible by the www-server you should be able to access it. What exact problems are you experiencing?

**Comment by juhajoki** [comment]
@hiren3897 closing this, if there's a still problem, please re-open.
