### ISSUE TITLE
There is a chance that MSE EME HEVC won’t play for the second time

### ISSUE THREAD

**Issue by xkening** [HbbTV-Association/ReferenceApplication#46]
When testing MSE-EME 1.2 HEVC 2160p video, there is a chance that it won’t play for the second time.
I found that the js error occurred.

> Uncaught (in promise) AbortError: The play() request was interrupted by a new load request. https://goo.gl/LdLk22 http://cdn.dashjs.org/latest/dash.all.min.js:3

I think the latest version of dash has solved this problem.

**Comment by juhajoki** [comment]
hello, thank you for the report. Which instance did you use? (testing/staging/production)?

**Comment by xkening** [comment]
RefAPP Staging HTML5

**Comment by juhajoki** [comment]
RefApp Testing in the MSE-EME mode is using the latest (nightly) dash.js, can you re-test if you can reproduce it with that?
