### ISSUE TITLE
Add Support for PlayReady CBCS

### ISSUE THREAD

**Issue by MarioKiefer** [HbbTV-Association/ReferenceApplication#47]
Hi,

could you please add support for PlayReady CBCS encryption, especially the 1:9 (encrypt:skip) pattern ?

Best Regards,
 Mario

**Comment by Murmur** [comment]
We are preparing a new release soon with a sample content CBCS_1:9 encryption scheme. Few reminders from Microsoft concerning Windows systems.

```
[Prior to PlayReady version 4.4](https://learn.microsoft.com/en-us/playready/overview/what-is-new/what-is-new-4-4#general), generating a license with a CBC key when the incoming Client Certificate is Windows and SL2000 throws an exception. 
This is because Windows Clients support CBC only on SL3000 units. 

It may be possible to deliver a license with a CBC key to a SL2000 Client, however, if this client is PlayReady version 4.0 minimum and declares support for the CBC mode.

Generating a license with a CBC key when the incoming Client Certificate is a device that uses a Porting Kit version prior to 4.0 will throw an exception. Generating a license with a CBC key when the incoming license request does not indicate support for AES CBC, will throw an exception.
```

**Comment by juhajoki** [comment]
First attempt of CBCS content available at **TESTING** instance, test 2.17 under "Playready 2" tab.

**Comment by Murmur** [comment]
Firefox(Win10, widevine) CBCS playback works if using `tenc.default_constant_IV, tenc.default_constant_IV_size` fields instead of `tenc.default_per_sample_IV_size` field. Refapp test content should work in firefox as well.

**Comment by jpiesing** [comment]
> Firefox(Win10, widevine) CBCS playback works if using `tenc.default_constant_IV, tenc.default_constant_IV_size` fields instead of `tenc.default_per_sample_IV_size` field. Refapp test content should work in firefox as well.

After comments in the IITF meeting, I did some research. Use of contstant_IV is required for cbcs by the MPEG common encryption specification (ISO 23001-7) in clause 10.4.1. Specifically;

> Constant IVs SHALL be used; default_Per_Sample_IV_Size and Per_Sample_IV_Size, SHALL be 0. 

I can't find any mention of this in CMAF or the CTA WAVE media profile but the common encryption spec underlies all these documents and is good enough.

**Comment by Murmur** [comment]
`CBCS(constantIV)` manifest, this is following the specs and works in Firefox as well.
https://refapp.hbbtv.org/videos/spring_1080p_cbcs_v1/drm/manifest.mpd

`CBCS(sampleIV, against the cbcs specs)` manifest, this is against the specs but some HbbTVs playback this one but not the previous one.
https://refapp.hbbtv.org/videos/spring_1080p_cbcs_v1_sampleiv/drm/manifest.mpd

**Comment by jpiesing** [comment]
> `CBCS(constantIV)` manifest, this is following the specs and works in Firefox as well. https://refapp.hbbtv.org/videos/spring_1080p_cbcs_v1/drm/manifest.mpd
> 
> `CBCS(sampleIV, against the cbcs specs)` manifest, this is against the specs but some HbbTVs playback this one but not the previous one. https://refapp.hbbtv.org/videos/spring_1080p_cbcs_v1_sampleiv/drm/manifest.mpd

I know it's what we agreed in the last meeting but I am really uncomfortable about continuing with cbcs+sampleIV when it's explicitly against the specs and this is a new technology for HbbTV.

**Comment by bobcampbell-eurofins** [comment]
Now available on the "Staging" instance: http://refapp.hbbtv.org/staging/catalogue/ item 2.17

**Comment by bobcampbell-eurofins** [comment]
We'll leave it open so people are aware its available on staging and we'll close in the next cycle when it hopefully moves to production.

**Comment by Murmur** [comment]
H264 `2.17.1 AVC 1080p CBCS_1:9` and h265 `2.17.2 HEVC 2160p CBCS_1:9` tests are in a production and staging applications.
https://refapp.hbbtv.org/production/catalogue/
https://refapp.hbbtv.org/staging/catalogue/

**Comment by Murmur** [comment]
Current test content is using the same `KeyID+EncKey` pair for CENC and CBCS encryption format of the "same video".
https://refapp.hbbtv.org/videos/00_llama_h264_v9/cenc/manifest_prcenc_1080p.mpd
https://refapp.hbbtv.org/videos/00_llama_h264_v9/cbcs/manifest_prcenc_1080p.mpd

This may introduce a side effect on some hbbtv televisions, first playback works but second fails (cenc-cbcs playback ordering) because an encryption scheme did not match with the first playback instance. Playback error may happen even if laurl license is not marked as a `valid for an offline persistence storage` .
