### ISSUE TITLE
 description of tests

### ISSUE THREAD

**Issue by ffallahi6303** [HbbTV-Association/ReferenceApplication#5]
I am using this application on 3 receivers, but there are some issues:
1- I couldn't find a difference between 2.1, 2.1.1 and 2.1.2, Where can I find a description of different tests?
2- I think test 1.2( HEVC 2160 p) is related to HbbTV2.0.1 and not HbbTV1.5. but this test is available in version 1.5 of the app. why?
3- It was good if after choosing each test, we read some sentences about the test and expectation of result. 
4- error messages is not clear.
5- what is DRM of live DRM?
6- what is the difference between HbbTV2.0.1 and HbbTV1.5 tests?

**Comment by juhajoki** [comment]
1. 2.1, 2.1.1 and 2.1.2 are using different methods of delivering the licence for playing the video asset
2. will be fixed
3. we can add some help inside the app as well
4. debug screen and log give more insight
5. Live is available in playready and marlin. Information has been added
6. they are using different video player
