### ISSUE TITLE
incorrect assumption about HTMLMediaElement decoder resource allocation

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#50]
From  https://redmine.hbbtv.org/issues/12215
![image](https://user-images.githubusercontent.com/8490792/155395032-6c76a442-4cd7-425f-8ad8-2d956981c7a0.png)

**Comment by jpiesing** [comment]
Feedback in redmine ...

The code to stop the broadcast is actually already in https://github.com/HbbTV-Association/ReferenceApplication/blob/master/src/videoplayer/videoplayer_html5.js, around line 729, but it is apparently never called.

**Comment by Murmur** [comment]
@jpiesing It's actually called on DRM content but for some reason not on nonDrm playback. After following the redmine #12215 chat and meetings we agreed on the following(?).

- always call `objBroadcast.bindToChannel() + objBroadcast.stop()` before starting a dash playback.
- call `objBroadcast.bindToChannel()` after stopping a dash playback, if object was added to DOM context.
- make this change on all three players (msememe, html5, oipf).

https://github.com/HbbTV-Association/ReferenceApplication/blob/9df685d8f63405c40def34862c3bf119ba7da39b/src/videoplayer/videoplayer_html5.js#L729
```
_mseeme.js=MSE (video tag mse + emeDrm)
_html5.js=Hbbtv2.x (video tag + oipfDrm)
_oipf.js=Hbbtv1.5(AvVideo obj + oipfDrm)
```

**Comment by aoakley-roku** [comment]
You might not need to change the A/V control version - the HbbTV specification says that if there is background broadcast playback then attempting to use an A/V control object will stop the broadcast playback.  When the A/V control object is stopped then the background broadcast playback is restarted.

I've got a potential fix for the HTML video element case, see pull request #52.  I've not made any attempt to restart playback afterwards.

**Comment by Murmur** [comment]
@aoakley-roku Thank you, PR is ok, changes are implemented and published to a [staging release](https://refapp.hbbtv.org/staging/catalogue/). I made similar change on hbbtv1.5(_oipf.js) and hbbtv2(_html5.js) players, broacast channel is resumed on `clearVideo()` function after a dash playback is stopped.

Github source repository is not updated yet as we are restructuring the integration to an internal development git repository.

**Comment by juhajoki** [comment]
github updated, PR merged (via the big sync push), ticket can be closed? @Murmur

**Comment by Murmur** [comment]
issue was resolved
