### ISSUE TITLE
Object #oipfDrm without sendDRMMessage

### ISSUE THREAD

**Issue by Pazzeo** [HbbTV-Association/ReferenceApplication#58]
Hello,

I have a problem with the oipfDrm obejct which does not have the function sendDRMMessage and everytime I have the following error in console: "sendDRMMessage" is not a function. Indeed, printing the functions of the object with 	console.log(Object.getOwnPropertyNames(this.oipfDrm)) I have only: onDRMMessageResult and onDRMRightsError.
Do you know why? 
I'm testing with Chrome and the extension RedOrbit

Thanks
Pazzeo

**Comment by Murmur** [comment]
Testing oipf DRM on a browser emulators most likely won't work, you may try `settings/enable mse-eme mode` to run on dashjs player. You need a real hbbtv hardware to test oipf interface.

https://chrome.google.com/webstore/search/hybridtv-dev-environment
https://chrome.google.com/webstore/detail/redorbit-hbbtv-emulator/mmgfafehampkahlmoahbjcjcmgmkppab?hl=en

**Comment by Pazzeo** [comment]
Thanks Murmur, I had the same feeling and indeed the test with a real hbbtv hardware is working well.
May I ask you if you know I could add custom headers before to call the sendDRMMessage ?

Thanks in advance
Pazzeo

**Comment by Murmur** [comment]
Unfortunately an internal oipf-drm(laurl) http request-response is a black box. Some drm license providers do require a custom http request headers such as auth tokens. You need to use a proxy script.

See this example to give you an idea. This script receives a playready payload from the client, use a hardcoded or `?laurl=xxxx`  for real laurl address, set headers given by `?mykey=myval` arguments, invoke the laurl, return a response. Similar approach works for widevine as well.
https://github.com/HbbTV-Association/ReferenceApplication/blob/master/tools/test/laurl_pr.php

**Comment by Murmur** [comment]
I have never used a relative `LA_URL` value so cannot comment on that one and then testing dozens of hbbtv devices is too much of an effort.

**Comment by Murmur** [comment]
closed, emulators don't simulate a full oipf interface.
