### ISSUE TITLE
change in version of app

### ISSUE THREAD

**Issue by ffallahi6303** [HbbTV-Association/ReferenceApplication#6]
version mode of application is changed to V 1.5 when the application is in ver 2.0.1.

**Comment by juhajoki** [comment]
can you clarify, please?

**Comment by ffallahi** [comment]
One issue is that there is not any return to menu in each test, if you finishing a test, the only way for returning to menue and start another test is you press exit key.I think that it should be solved.


My question was about following issue: I saw it in some receivers not all.
When you are in ver 2.0.1 of app and you finished a test as mentioned in above, you have to press exit to return to menu and start a new test. In this state, application will be changed to ver1.5 and you have to set it on ver2.0.1 again.

**Comment by juhajoki** [comment]
looks like oipf (1.5) player is not returning to main menu after test. 

BACK key should be used to get back to main menu.
EXIT key will relaunch the application, and it can revert to 1.5 if the user agent of the receiver indicates HbbTV 1.2.1 (1.5) support.

Closing this and opening a new ticket about oipf player issue.
