### ISSUE TITLE
Add note about data collection to readme

### ISSUE THREAD

**Issue by juhajoki** [HbbTV-Association/ReferenceApplication#65]
We should clarify how and when data is collected when application is run. First attempt of the text:

> When the live instance (refapp.hbbtv.org) is accessed it is logged in the server access log. This log is never analyzed unless explicitly requested by HbbTV association to obtain for example data about the diversity of devices running the app.
> 
> The access data is tabulated monhtly as total visitors, total requests and amount of data transferred. This data is shared in the HbbTV IITF Reference Appliation status report. No data is ever collected about the results of individual tests run by other people. 
> 
> 100% of the test data in the anonymized result sheet (available to HbbTV members) is collected by test engineers of Sofia Digital, using the devices in the test laboratory of Sofia Digital. Sofia maintains internal and confidential data about specific models and results, and this data is available to manufacturers in question upon request. Sofia also sends this data periodically to manufacturers to discuss findings and possible bugs in the test materials or specific devices.

A shorter form could also be added to application itself.

**Comment by bobcampbell-eurofins** [comment]
How about this as intro/context:

>This tool is provided by the HbbTV Association, a cooperation between broadcasters, operators, manufacturers and technology providers worldwide. It is a non-profit association registered in Switzerland, and is as such constrained by competition law which generally forbids coordination of activity, except standardization activity which produces clear benefits for consumers. Therefore, while the provision of this tool has been made to encourage and facilitate standardization around DRM, the HbbTV Association has chosen not to share individual device results with its own members or beyond, to avoid any risk of competitors gaining an advantage through this data.

**Comment by juhajoki** [comment]
so the complete text would be a combination of these?

**Comment by bobcampbell-eurofins** [comment]
Yes:

>This tool is provided by the HbbTV Association, a cooperation between broadcasters, operators, manufacturers and technology providers worldwide. It is a non-profit association registered in Switzerland, and is as such constrained by competition law which generally forbids coordination of activity, except standardization activity which produces clear benefits for consumers. Therefore, while the provision of this tool has been made to encourage and facilitate standardization around DRM, the HbbTV Association has chosen not to share individual device results with its own members or beyond, to avoid any risk of competitors gaining an advantage through this data.

>When the live instance (refapp.hbbtv.org) is accessed it is logged in the server access log. This log is never analysed unless explicitly requested by HbbTV association to obtain for example data about the diversity of devices running the app.

>The access data is tabulated monthly as total visitors, total requests and amount of data transferred. This data is shared in the HbbTV IITF Reference Application status report. No data is ever collected about the results of individual tests run by other people.

>100% of the test data in the anonymized result sheet (available to HbbTV members) is collected by test engineers of Sofia Digital, using the devices in the test laboratory of Sofia Digital. Sofia maintains internal and confidential data about specific models and results, and this data is available to manufacturers in question upon request. Sofia also sends this data periodically to manufacturers to discuss findings and possible bugs in the test materials or specific devices.

I think then the proposed "about" box in #30 could just refer to the readme alongside the already suggested data collection text in that ticket. I note that #30 was closed with the intent to roll it into #54 but there's a risk that ticket would miss this part - do you think we should re-open #30?

**Comment by Murmur** [comment]
Ticket #30 `Settings/About the application` text box has a brief data collection text and this github project link for more information.
