### ISSUE TITLE
AD media elements were not cleared properly in MSE-EME mode

### ISSUE THREAD

**Issue by shengpingl** [HbbTV-Association/ReferenceApplication#66]
Hi,
We run _**TC 1.5 "Advert Insertion"**_  on hbbtv devices and found that AD player was not destroyed properly on 'BACK' key press.
After investigation we found that there might be some errors inside function _**VideoPlayerEME.prototype.clearAds**_ of source:
http://localhost/ReferenceApplication/src/videoplayer/videoplayer_mse-eme.js?version=1675747035
1. **self** is window object by default, we should override it by **VideoPlayerEME** object at function entry point, like we what did inside function **VideoPlayerEME.prototype.clearVideo**
    ```
     var self = this;
    ```
2.  As HTML5 video element does not support **_stop()_** method, we should remove call of it to avoid js runtime exceptions.
```
      //self.adPlayer[0].stop();
      //self.adPlayer[1].stop();
```

So the final suggested patch is:
```
diff --git a/src/videoplayer/videoplayer_mse-eme.js b/src/videoplayer/videoplayer_mse-eme.js
index 108ab64..39c6f80 100644
--- a/src/videoplayer/videoplayer_mse-eme.js
+++ b/src/videoplayer/videoplayer_mse-eme.js
@@ -818,10 +818,9 @@ VideoPlayerEME.prototype.clearVideo = function(){
 };
 
 VideoPlayerEME.prototype.clearAds = function(){
+       var self = this;
        try{
                if( self.adPlayer ){
-                       self.adPlayer[0].stop();
-                       self.adPlayer[1].stop();
                        $( self.adPlayer[0] ).addClass("hide");
                        $( self.adPlayer[1] ).addClass("hide");
```

Please take a look at this issue, thanks!

B.R.
shengpingl

**Comment by juhajoki** [comment]
thank you for the detailed report, we will take a look.

**Comment by Murmur** [comment]
submitted changes to a source code and staging UI
https://refapp.hbbtv.org/staging/catalogue

**Comment by Murmur** [comment]
@linzj1 See this mpeg.ts test stream, it should have links to a prod and staging versions. You should use staging to see the latest updates as production cycle is few times a year.
https://github.com/HbbTV-Association/ReferenceApplication#mpeg-2-ts
