### ISSUE TITLE
Multiple MDP EventStream/Event elements, native player may want to group by schemeId

### ISSUE THREAD

**Issue by Murmur** [HbbTV-Association/ReferenceApplication#67]
Some Hbbtv native players want multiple events grouped by the same `schemeIdUri+value` identifiers. Dash specs allow 0..n EventStream and 0..n Event elements.

Dashjs(mse) player supports multiple `EventStream (identical schemeIdUri+value)` each having just one `Event` element.

This example is a compatible with hbbtv native players.
```
...
<Period id="p57538523" duration="PT15.360S">
   <EventStream schemeIdUri="http://hbbtv.org/refapp" value="1a2b3c" timescale="1000">
      <Event presentationTime="1000" duration="3000" id="57538523">MPD event(p57538523, period start)</Event>
      <Event presentationTime="12360" duration="3000" id="1057538523">MPD event(p57538523, ending soon)</Event>
   </EventStream>
   <AdaptationSet id="1" contentType="video" lang="eng" maxFrameRate="25" maxWidth="1280" maxHeight="720" par="16:9" segmentAlignment="true" startWithSAP="1">
...
```

**Comment by jpiesing** [comment]
The native player example is what I would expect. 
Did you report a bug with dash.js? Are they  just following the DASH-IF spec?

**Comment by Murmur** [comment]
@jpiesing I edited my comment, tried to write earlier dashjs supports both formats.

**Comment by Murmur** [comment]
@jpiesing Edited the first comment to list `native,dashjs,live,static` combinations.

**Comment by jpiesing** [comment]
Not supporting events in a live MPD is a bug in the player.
