### ISSUE TITLE
add recent streams to https://refapp.hbbtv.org/videos/

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#69]
The recent streams used in production and staging should be available via https://refapp.hbbtv.org/videos/

**Comment by jpiesing** [comment]
From the liasion letter ...

- New Playready security levels and signaling tests, including Security Level 2000 with different Key ID tests, Security Level 3000 for video and SL 2000 for audio and new ‘playready.recommendation’ scheme tests with different KIDs.
- A CBCS encryption scheme test.
- New DASH Multiperiod tests simulating the results of SSAI including tests for Live multiperiod, live multiperiod with playready and for reference a static multiperiod test. All tests include ad breaks, subtitles and multiple audio tracks. 
- Multi-DRM including Widevine and Playready. The streams cover several combinations including only Playready in manifest, only Widevine in manifest or both in manifest. 
- Persistent licenses. This is in response to market feedback that real-world implementations sometimes always request a new license even when a suitable one is available, which defeats the point of using them and may incur cost for content providers.

**Comment by Murmur** [comment]
Updated `index.html` page available.
https://refapp.hbbtv.org/videos/

**Comment by jpiesing** [comment]
> Updated `index.html` page available: https://refapp.hbbtv.org/videos/
> 
> Updated Microsoft PlayReady to list cbcs and multikey `laurl` examples: https://refapp.hbbtv.org/videos/keys_microsofttest.json

I can see the CBCS streams there.
I can see the LAURL proxies which I guess are for the persitent license tests?
I can see multi DRM at the end of the page.
I can't see any mention of SL3000, I would have expected the existing streams to be SL2000 and new SL3000 streams to be added. Am I missing someting? 
I also can't see any mention of the multiperiod streams. Am I missing something here?

**Comment by Murmur** [comment]
Added `PlayReady security level, CENC and CBCS` information. Manifest and segments are always the same for several tests, to choose a security level or CENC/CBCS is specified in an appropriate Microsoft test LaUrl values.

Also `Spring, multikey, KID=12371236` description updated to indicate usability in SL3000 testing. SL2000 may use any traditional singlekey or this multikey content.

Added `MultiPeriod` information, url parameters may be used to control a manifest reload method(mpd event or constant minimunUpdatePeriod), drm, with or wihtout advert breaks.

**Comment by jpiesing** [comment]
Is all the historical content added to the videos page?

For example, I notice that the word "chunked" does not appear on the page.

**Comment by Murmur** [comment]
Added link to `index_2019.html (previous test content)` page.
https://refapp.hbbtv.org/videos/
