### ISSUE TITLE
possibility to include external content in DASH-DRM reference app

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#70]
One of the points from the Q&A when I presented the reference app to DASH-IF was offers of test content from some of the companies there.
We should consider if we would want to enable this. For example, another tab in the UI. If we would want to enable this, then we we should consider the conditions and details. For example, presumably we would want each each company concerned to provide a  contact if someone thinks there is a problem with the content.

**Comment by Murmur** [comment]
New tab with an external content items or "Other" tab with 1..n link item to RefApp/other instance. Instance could use own tabsheets.

**Comment by jpiesing** [comment]
I'm told that one of the large DASH encoder / packager providers has made a number of streams available to one of the HbbTV stack providers for some years now for integration testing. They offered to make them available via the reference app. As did another DASH-IF member with test streams.
