### ISSUE TITLE
multi-period DASH - use different encoder for the simulated ads

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#71]
I'm told that one of the challenges for SSAI is that the ads are normally encoded using a different encoder from the content. This change can upset players.
Is it possible to update our multi-Period test and use a different encoder (or at least different encoder settings) or the simulated ad?

**Comment by Murmur** [comment]
We have this settings, toolset is ffmpeg(encoding) and mp4box(dash segmenting):
**Main** `H264, 360p(Main@3.0), 720p(High@4.0), 1080p(High@4.0), 25fps, segdur 3.84s`
**Advert** `H264, 360p(Main@3.0), 720p(High@4.0), 1080p(High@4.0), 25fps, segdur 2s`

We could create few advert breaks such as different set of resolutions `405p(Main@3.0), 720p(High@3.2), 25fps, segdur 4s, etc..` and use ffmpeg to write advert segments ("different packager"). Insert new advert breaks to an existing multiperiod configuration.

I have not studied how different `codec+bitrate+resolution+audio` settings adverts use in other SSAI contents.  I believe most try to match a primary codec(h264,h265) anyway.

**Comment by Murmur** [comment]
@jpiesing I have made a new advert using `ffmpeg encoder + fmpeg dash packager | h264 704x396(main@3.0) 600Kbit, h264 1024x576(high@3.2) 1000Kbit` specs. Main content is using a different packager(mp4box) and resolutions, so advert switch is not a bit-by-bit specs identical.
https://refapp.hbbtv.org/videos/test01_v3_ff/manifest.mpd

**Comment by Murmur** [comment]
RefappStaging has a new `Multiperiod/6.8 Live (Playready, 2s reload interval, different packagers)` test case.
https://refapp.hbbtv.org/staging/catalogue/

Some adverts use a mp4box packager content.
Some adverts use a ffmpeg packager content, see a header text `(dash_ffmpeg)` in a video. This advert also use a completely different resolutions and segment duration, it does not match to a main content or other adverts. Players need to act accordingly on a period switching.
`dash_ffmpeg: v1=704x396/600Kbit, v2=1024x576/1000Kbit, segdur=4s`
