### ISSUE TITLE
encryption, seig boxes, key rotation

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/ReferenceApplication#73]
The following discussion in the public MPEG github seems that it could be relevant.

https://github.com/MPEGGroup/CMAF/issues/36#issuecomment-1633800469

How does this discussion relate to what we have done? Are there gaps in what we have done?

**Comment by Murmur** [comment]
`Mixture of clear and protected samples` : Refapp encrypts all samples and do not write a clear(unencrypted) samples in the beginning or anywhere else in the segment file. 

Atom table `seig(CencSampleEncryption group)` is not written to an encrypted content.

However this is something must double check in an inband (segment files 1.m4s) KeyID rotation content if both `PSSH` and  `SEIG` box is written to segment files.

**Comment by jpiesing** [comment]
@Murmur If the reference app content doesn't use seig boxes, is this a gap? Should we have a stream that uses them?

**Comment by jpiesing** [comment]
This was discussed in the September 7th IITF meeting and in the one 2 weeks before.
The conclusion was that this is not used in the real world.
Anyone who disagrees is welcome to re-open the issue if they add new information.
