### ISSUE TITLE
Invalid HTTPS certificate setup on refapp.hbbtv.org

### ISSUE THREAD

**Issue by emarsden** [HbbTV-Association/ReferenceApplication#80]
The HTTPS (TLS/SSL) certificate on refapp.hbbtv.org was updated a few days ago (the certificate is dated 24 Nov 2023, signed by Gandi). It is incorrectly configured: it does not include the chain of certificates to the root of trust. This means that standard commandline applications like wget are not able to connect to the site, because they don't fetch missing certificates online (unlike a web browser). 

See this site for confirmation:

   https://whatsmychaincert.com/?refapp.hbbtv.org

Fix: modify the TLS certificate on the server to include the intermediate certificates provided by Gandi.

**Comment by juhajoki** [comment]
@emarsden thanks for the report, will check asap.

**Comment by juhajoki** [comment]
@emarsden fixed.
